<?php

namespace Carbon_Fields\Field;

class Icon_Field extends Field {
	/*
	 * Properties
	 */
	protected $icons;
	protected $icon_type = 'font-awesome';
	protected $icon_class;

	/**
	 * to_json()
	 * 
	 * You can use this method to modify the field properties that are added to the JSON object.
	 * The JSON object is used by the Backbone Model and the Underscore template.
	 * 
	 * @param bool $load  Should the value be loaded from the database or use the value from the current instance.
	 * @return array
	 */
	function to_json( $load ) {

		$field_data = parent::to_json( $load ); // do not delete

		switch ( $this->icon_type ) {

			case 'font-awesome' : { 
				$this->icons 	  = $this->get_font_awesome_icons();
				$this->icon_class = 'fa';
				break;
			}

			case 'dashicons' : {
				$this->icons 	  = $this->get_dashboard_icons();
				$this->icon_class = 'dashicons-before';
				break;
			}

		}

		$field_data = array_merge( $field_data, array(
			'icons' 	 => $this->icons,
			'icon_class' => $this->icon_class
		));

		return $field_data;

	}

	/**
	 * template()
	 *
	 * Prints the main Underscore template
	 **/
	function template() { ?>

		<div class="icons-container">

			<div class="icons-left-section">
				<input class="icon-field-value" id="{{{ id }}}" type="hidden" name="{{{ name }}}" value="{{ value }}" />
				<span class="{{{icon_class}}} icon-preview {{ value }}"></span>
				<span class="icon-type" data-icon-type="{{{icon_class}}}">
			</div>

			<div class="icon-right-section">

				<input type="text" class="icons-search-field" placeholder="<?php _e('Search', 'crb'); ?>" />
				
				<# if ( icons ) { #>
					<span class="no-results"><?php _e('No results', 'crb'); ?></span>
					<ul class="font-awesome-icons">						
						<# _.each(icons, function(icon) { #>
							<li> <i data-value="{{{icon}}}" class="{{{icon_class}}} {{{icon}}}"></i> </li>
						<# }) #>
					</ul>
				<# } #>

			</div>

		</div>
		<?php
	}

	/**
	 * admin_enqueue_scripts()
	 * 
	 * This method is called in the admin_enqueue_scripts action. It is called once per field type.
	 * Use this method to enqueue CSS + JavaScript files.
	 * 
	 */
	function admin_enqueue_scripts() {

		$dir = plugin_dir_url( __FILE__ );

		# Enqueue JS
		wp_enqueue_script( 'carbon-field-icon', $dir . 'js/field.js', array( 'carbon-fields' ) );

		# Enqueue CSS
		wp_enqueue_style( 'carbon-field-icon', $dir . 'css/field.css' );
		wp_enqueue_style( 'carbon-font-awesome', $dir . 'css/font-awesome.css' );
		wp_enqueue_style( 'carbon-dashicons', $dir . 'css/dashicons.css');
		wp_enqueue_style( 'dashicons' );

	}

	function from($type) {
		$this->icon_type = $type;
		return $this;
	}


	function get_font_awesome_icons() {

		return array(
			'fa-500px',
			'fa-adjust',
			'fa-adn',
			'fa-align-center',
			'fa-align-justify',
			'fa-align-left',
			'fa-align-right',
			'fa-amazon',
			'fa-ambulance',
			'fa-anchor',
			'fa-android',
			'fa-angellist',
			'fa-angle-double-down',
			'fa-angle-double-left',
			'fa-angle-double-right',
			'fa-angle-double-up',
			'fa-angle-down',
			'fa-angle-left',
			'fa-angle-right',
			'fa-angle-up',
			'fa-apple',
			'fa-archive',
			'fa-area-chart',
			'fa-arrow-circle-down',
			'fa-arrow-circle-left',
			'fa-arrow-circle-o-down',
			'fa-arrow-circle-o-left',
			'fa-arrow-circle-o-right',
			'fa-arrow-circle-o-up',
			'fa-arrow-circle-right',
			'fa-arrow-circle-up',
			'fa-arrow-down',
			'fa-arrow-left',
			'fa-arrow-right',
			'fa-arrow-up',
			'fa-arrows',
			'fa-arrows-alt',
			'fa-arrows-h',
			'fa-arrows-v',
			'fa-asterisk',
			'fa-at',
			'fa-backward',
			'fa-balance-scale',
			'fa-ban',
			'fa-bar-chart',
			'fa-barcode',
			'fa-bars',
			'fa-battery-empty',
			'fa-battery-full',
			'fa-battery-half',
			'fa-battery-quarter',
			'fa-battery-three-quarters',
			'fa-bed',
			'fa-beer',
			'fa-behance',
			'fa-behance-square',
			'fa-bell',
			'fa-bell-o',
			'fa-bell-slash',
			'fa-bell-slash-o',
			'fa-bicycle',
			'fa-binoculars',
			'fa-birthday-cake',
			'fa-bitbucket',
			'fa-bitbucket-square',
			'fa-black-tie',
			'fa-bold',
			'fa-bolt',
			'fa-bomb',
			'fa-book',
			'fa-bookmark',
			'fa-bookmark-o',
			'fa-briefcase',
			'fa-btc',
			'fa-bug',
			'fa-building',
			'fa-building-o',
			'fa-bullhorn',
			'fa-bullseye',
			'fa-bus',
			'fa-buysellads',
			'fa-calculator',
			'fa-calendar',
			'fa-calendar-check-o',
			'fa-calendar-minus-o',
			'fa-calendar-o',
			'fa-calendar-plus-o',
			'fa-calendar-times-o',
			'fa-camera',
			'fa-camera-retro',
			'fa-car',
			'fa-caret-down',
			'fa-caret-left',
			'fa-caret-right',
			'fa-caret-square-o-down',
			'fa-caret-square-o-left',
			'fa-caret-square-o-right',
			'fa-caret-square-o-up',
			'fa-caret-up',
			'fa-cart-arrow-down',
			'fa-cart-plus',
			'fa-cc',
			'fa-cc-amex',
			'fa-cc-diners-club',
			'fa-cc-discover',
			'fa-cc-jcb',
			'fa-cc-mastercard',
			'fa-cc-paypal',
			'fa-cc-stripe',
			'fa-cc-visa',
			'fa-certificate',
			'fa-chain-broken',
			'fa-check',
			'fa-check-circle',
			'fa-check-circle-o',
			'fa-check-square',
			'fa-check-square-o',
			'fa-chevron-circle-down',
			'fa-chevron-circle-left',
			'fa-chevron-circle-right',
			'fa-chevron-circle-up',
			'fa-chevron-down',
			'fa-chevron-left',
			'fa-chevron-right',
			'fa-chevron-up',
			'fa-child',
			'fa-chrome',
			'fa-circle',
			'fa-circle-o',
			'fa-circle-o-notch',
			'fa-circle-thin',
			'fa-clipboard',
			'fa-clock-o',
			'fa-clone',
			'fa-cloud',
			'fa-cloud-download',
			'fa-cloud-upload',
			'fa-code',
			'fa-code-fork',
			'fa-codepen',
			'fa-coffee',
			'fa-cog',
			'fa-cogs',
			'fa-columns',
			'fa-comment',
			'fa-comment-o',
			'fa-commenting',
			'fa-commenting-o',
			'fa-comments',
			'fa-comments-o',
			'fa-compass',
			'fa-compress',
			'fa-connectdevelop',
			'fa-contao',
			'fa-copyright',
			'fa-creative-commons',
			'fa-credit-card',
			'fa-crop',
			'fa-crosshairs',
			'fa-css3',
			'fa-cube',
			'fa-cubes',
			'fa-cutlery',
			'fa-dashcube',
			'fa-database',
			'fa-delicious',
			'fa-desktop',
			'fa-deviantart',
			'fa-diamond',
			'fa-digg',
			'fa-dot-circle-o',
			'fa-download',
			'fa-dribbble',
			'fa-dropbox',
			'fa-drupal',
			'fa-eject',
			'fa-ellipsis-h',
			'fa-ellipsis-v',
			'fa-empire',
			'fa-envelope',
			'fa-envelope-o',
			'fa-envelope-square',
			'fa-eraser',
			'fa-eur',
			'fa-exchange',
			'fa-exclamation',
			'fa-exclamation-circle',
			'fa-exclamation-triangle',
			'fa-expand',
			'fa-expeditedssl',
			'fa-external-link',
			'fa-external-link-square',
			'fa-eye',
			'fa-eye-slash',
			'fa-eyedropper',
			'fa-facebook',
			'fa-facebook-official',
			'fa-facebook-square',
			'fa-fast-backward',
			'fa-fast-forward',
			'fa-fax',
			'fa-female',
			'fa-fighter-jet',
			'fa-file',
			'fa-file-archive-o',
			'fa-file-audio-o',
			'fa-file-code-o',
			'fa-file-excel-o',
			'fa-file-image-o',
			'fa-file-o',
			'fa-file-pdf-o',
			'fa-file-powerpoint-o',
			'fa-file-text',
			'fa-file-text-o',
			'fa-file-video-o',
			'fa-file-word-o',
			'fa-files-o',
			'fa-film',
			'fa-filter',
			'fa-fire',
			'fa-fire-extinguisher',
			'fa-firefox',
			'fa-flag',
			'fa-flag-checkered',
			'fa-flag-o',
			'fa-flask',
			'fa-flickr',
			'fa-floppy-o',
			'fa-folder',
			'fa-folder-o',
			'fa-folder-open',
			'fa-folder-open-o',
			'fa-font',
			'fa-fonticons',
			'fa-forumbee',
			'fa-forward',
			'fa-foursquare',
			'fa-frown-o',
			'fa-futbol-o',
			'fa-gamepad',
			'fa-gavel',
			'fa-gbp',
			'fa-genderless',
			'fa-get-pocket',
			'fa-gg',
			'fa-gg-circle',
			'fa-gift',
			'fa-git',
			'fa-git-square',
			'fa-github',
			'fa-github-alt',
			'fa-github-square',
			'fa-glass',
			'fa-globe',
			'fa-google',
			'fa-google-plus',
			'fa-google-plus-square',
			'fa-google-wallet',
			'fa-graduation-cap',
			'fa-gratipay',
			'fa-h-square',
			'fa-hacker-news',
			'fa-hand-lizard-o',
			'fa-hand-o-down',
			'fa-hand-o-left',
			'fa-hand-o-right',
			'fa-hand-o-up',
			'fa-hand-paper-o',
			'fa-hand-peace-o',
			'fa-hand-pointer-o',
			'fa-hand-rock-o',
			'fa-hand-scissors-o',
			'fa-hand-spock-o',
			'fa-hdd-o',
			'fa-header',
			'fa-headphones',
			'fa-heart',
			'fa-heart-o',
			'fa-heartbeat',
			'fa-history',
			'fa-home',
			'fa-hospital-o',
			'fa-hourglass',
			'fa-hourglass-end',
			'fa-hourglass-half',
			'fa-hourglass-o',
			'fa-hourglass-start',
			'fa-houzz',
			'fa-html5',
			'fa-i-cursor',
			'fa-ils',
			'fa-inbox',
			'fa-indent',
			'fa-industry',
			'fa-info',
			'fa-info-circle',
			'fa-inr',
			'fa-instagram',
			'fa-internet-explorer',
			'fa-ioxhost',
			'fa-italic',
			'fa-joomla',
			'fa-jpy',
			'fa-jsfiddle',
			'fa-key',
			'fa-keyboard-o',
			'fa-krw',
			'fa-language',
			'fa-laptop',
			'fa-lastfm',
			'fa-lastfm-square',
			'fa-leaf',
			'fa-leanpub',
			'fa-lemon-o',
			'fa-level-down',
			'fa-level-up',
			'fa-life-ring',
			'fa-lightbulb-o',
			'fa-line-chart',
			'fa-link',
			'fa-linkedin',
			'fa-linkedin-square',
			'fa-linux',
			'fa-list',
			'fa-list-alt',
			'fa-list-ol',
			'fa-list-ul',
			'fa-location-arrow',
			'fa-lock',
			'fa-long-arrow-down',
			'fa-long-arrow-left',
			'fa-long-arrow-right',
			'fa-long-arrow-up',
			'fa-magic',
			'fa-magnet',
			'fa-male',
			'fa-map',
			'fa-map-marker',
			'fa-map-o',
			'fa-map-pin',
			'fa-map-signs',
			'fa-mars',
			'fa-mars-double',
			'fa-mars-stroke',
			'fa-mars-stroke-h',
			'fa-mars-stroke-v',
			'fa-maxcdn',
			'fa-meanpath',
			'fa-medium',
			'fa-medkit',
			'fa-meh-o',
			'fa-mercury',
			'fa-microphone',
			'fa-microphone-slash',
			'fa-minus',
			'fa-minus-circle',
			'fa-minus-square',
			'fa-minus-square-o',
			'fa-mobile',
			'fa-money',
			'fa-moon-o',
			'fa-motorcycle',
			'fa-mouse-pointer',
			'fa-music',
			'fa-neuter',
			'fa-newspaper-o',
			'fa-object-group',
			'fa-object-ungroup',
			'fa-odnoklassniki',
			'fa-odnoklassniki-square',
			'fa-opencart',
			'fa-openid',
			'fa-opera',
			'fa-optin-monster',
			'fa-outdent',
			'fa-pagelines',
			'fa-paint-brush',
			'fa-paper-plane',
			'fa-paper-plane-o',
			'fa-paperclip',
			'fa-paragraph',
			'fa-pause',
			'fa-paw',
			'fa-paypal',
			'fa-pencil',
			'fa-pencil-square',
			'fa-pencil-square-o',
			'fa-phone',
			'fa-phone-square',
			'fa-picture-o',
			'fa-pie-chart',
			'fa-pied-piper',
			'fa-pied-piper-alt',
			'fa-pinterest',
			'fa-pinterest-p',
			'fa-pinterest-square',
			'fa-plane',
			'fa-play',
			'fa-play-circle',
			'fa-play-circle-o',
			'fa-plug',
			'fa-plus',
			'fa-plus-circle',
			'fa-plus-square',
			'fa-plus-square-o',
			'fa-power-off',
			'fa-print',
			'fa-puzzle-piece',
			'fa-qq',
			'fa-qrcode',
			'fa-question',
			'fa-question-circle',
			'fa-quote-left',
			'fa-quote-right',
			'fa-random',
			'fa-rebel',
			'fa-recycle',
			'fa-reddit',
			'fa-reddit-square',
			'fa-refresh',
			'fa-registered',
			'fa-renren',
			'fa-repeat',
			'fa-reply',
			'fa-reply-all',
			'fa-retweet',
			'fa-road',
			'fa-rocket',
			'fa-rss',
			'fa-rss-square',
			'fa-rub',
			'fa-safari',
			'fa-scissors',
			'fa-search',
			'fa-search-minus',
			'fa-search-plus',
			'fa-sellsy',
			'fa-server',
			'fa-share',
			'fa-share-alt',
			'fa-share-alt-square',
			'fa-share-square',
			'fa-share-square-o',
			'fa-shield',
			'fa-ship',
			'fa-shirtsinbulk',
			'fa-shopping-cart',
			'fa-sign-in',
			'fa-sign-out',
			'fa-signal',
			'fa-simplybuilt',
			'fa-sitemap',
			'fa-skyatlas',
			'fa-skype',
			'fa-slack',
			'fa-sliders',
			'fa-slideshare',
			'fa-smile-o',
			'fa-sort',
			'fa-sort-alpha-asc',
			'fa-sort-alpha-desc',
			'fa-sort-amount-asc',
			'fa-sort-amount-desc',
			'fa-sort-asc',
			'fa-sort-desc',
			'fa-sort-numeric-asc',
			'fa-sort-numeric-desc',
			'fa-soundcloud',
			'fa-space-shuttle',
			'fa-spinner',
			'fa-spoon',
			'fa-spotify',
			'fa-square',
			'fa-square-o',
			'fa-stack-exchange',
			'fa-stack-overflow',
			'fa-star',
			'fa-star-half',
			'fa-star-half-o',
			'fa-star-o',
			'fa-steam',
			'fa-steam-square',
			'fa-step-backward',
			'fa-step-forward',
			'fa-stethoscope',
			'fa-sticky-note',
			'fa-sticky-note-o',
			'fa-stop',
			'fa-street-view',
			'fa-strikethrough',
			'fa-stumbleupon',
			'fa-stumbleupon-circle',
			'fa-subscript',
			'fa-subway',
			'fa-suitcase',
			'fa-sun-o',
			'fa-superscript',
			'fa-table',
			'fa-tablet',
			'fa-tachometer',
			'fa-tag',
			'fa-tags',
			'fa-tasks',
			'fa-taxi',
			'fa-television',
			'fa-tencent-weibo',
			'fa-terminal',
			'fa-text-height',
			'fa-text-width',
			'fa-th',
			'fa-th-large',
			'fa-th-list',
			'fa-thumb-tack',
			'fa-thumbs-down',
			'fa-thumbs-o-down',
			'fa-thumbs-o-up',
			'fa-thumbs-up',
			'fa-ticket',
			'fa-times',
			'fa-times-circle',
			'fa-times-circle-o',
			'fa-tint',
			'fa-toggle-off',
			'fa-toggle-on',
			'fa-trademark',
			'fa-train',
			'fa-transgender',
			'fa-transgender-alt',
			'fa-trash',
			'fa-trash-o',
			'fa-tree',
			'fa-trello',
			'fa-tripadvisor',
			'fa-trophy',
			'fa-truck',
			'fa-try',
			'fa-tty',
			'fa-tumblr',
			'fa-tumblr-square',
			'fa-twitch',
			'fa-twitter',
			'fa-twitter-square',
			'fa-umbrella',
			'fa-underline',
			'fa-undo',
			'fa-university',
			'fa-unlock',
			'fa-unlock-alt',
			'fa-upload',
			'fa-usd',
			'fa-user',
			'fa-user-md',
			'fa-user-plus',
			'fa-user-secret',
			'fa-user-times',
			'fa-users',
			'fa-venus',
			'fa-venus-double',
			'fa-venus-mars',
			'fa-viacoin',
			'fa-video-camera',
			'fa-vimeo',
			'fa-vimeo-square',
			'fa-vine',
			'fa-vk',
			'fa-volume-down',
			'fa-volume-off',
			'fa-volume-up',
			'fa-weibo',
			'fa-weixin',
			'fa-whatsapp',
			'fa-wheelchair',
			'fa-wifi',
			'fa-wikipedia-w',
			'fa-windows',
			'fa-wordpress',
			'fa-wrench',
			'fa-xing',
			'fa-xing-square',
			'fa-y-combinator',
			'fa-yahoo',
			'fa-yelp',
			'fa-youtube',
			'fa-youtube-play',
			'fa-youtube-square',
		);
	}

	function get_dashboard_icons() {
		return array(
			'dashicons-menu',
			'dashicons-dashboard',
			'dashicons-admin-site',
			'dashicons-admin-media',
			'dashicons-admin-page',
			'dashicons-admin-comments',
			'dashicons-admin-appearance',
			'dashicons-admin-plugins',
			'dashicons-admin-users',
			'dashicons-admin-tools',
			'dashicons-admin-settings',
			'dashicons-admin-network',
			'dashicons-admin-generic',
			'dashicons-admin-home',
			'dashicons-admin-collapse',
			'dashicons-admin-links',
			'dashicons-admin-post',
			'dashicons-format-standard',
			'dashicons-format-image',
			'dashicons-format-gallery',
			'dashicons-format-audio',
			'dashicons-format-video',
			'dashicons-format-links',
			'dashicons-format-chat',
			'dashicons-format-status',
			'dashicons-format-aside',
			'dashicons-format-quote',
			'dashicons-welcome-write-blog',
			'dashicons-welcome-edit-page',
			'dashicons-welcome-add-page',
			'dashicons-welcome-view-site',
			'dashicons-welcome-widgets-menus',
			'dashicons-welcome-comments',
			'dashicons-welcome-learn-more',
			'dashicons-image-crop',
			'dashicons-image-rotate-left',
			'dashicons-image-rotate-right',
			'dashicons-image-flip-vertical',
			'dashicons-image-flip-horizontal',
			'dashicons-undo',
			'dashicons-redo',
			'dashicons-editor-bold',
			'dashicons-editor-italic',
			'dashicons-editor-ul',
			'dashicons-editor-ol',
			'dashicons-editor-quote',
			'dashicons-editor-alignleft',
			'dashicons-editor-aligncenter',
			'dashicons-editor-alignright',
			'dashicons-editor-insertmore',
			'dashicons-editor-spellcheck',
			'dashicons-editor-distractionfree',
			'dashicons-editor-expand',
			'dashicons-editor-contract',
			'dashicons-editor-kitchensink',
			'dashicons-editor-underline',
			'dashicons-editor-justify',
			'dashicons-editor-textcolor',
			'dashicons-editor-paste-word',
			'dashicons-editor-paste-text',
			'dashicons-editor-removeformatting',
			'dashicons-editor-video',
			'dashicons-editor-customchar',
			'dashicons-editor-outdent',
			'dashicons-editor-indent',
			'dashicons-editor-help',
			'dashicons-editor-strikethrough',
			'dashicons-editor-unlink',
			'dashicons-editor-rtl',
			'dashicons-editor-break',
			'dashicons-editor-code',
			'dashicons-editor-paragraph',
			'dashicons-align-left',
			'dashicons-align-right',
			'dashicons-align-center',
			'dashicons-align-none',
			'dashicons-lock',
			'dashicons-calendar',
			'dashicons-visibility',
			'dashicons-post-status',
			'dashicons-edit',
			'dashicons-post-trash',
			'dashicons-trash',
			'dashicons-external',
			'dashicons-arrow-up',
			'dashicons-arrow-down',
			'dashicons-arrow-left',
			'dashicons-arrow-right',
			'dashicons-arrow-up-alt',
			'dashicons-arrow-down-alt',
			'dashicons-arrow-left-alt',
			'dashicons-arrow-right-alt',
			'dashicons-arrow-up-alt2',
			'dashicons-arrow-down-alt2',
			'dashicons-arrow-left-alt2',
			'dashicons-arrow-right-alt2',
			'dashicons-leftright',
			'dashicons-sort',
			'dashicons-randomize',
			'dashicons-list-view',
			'dashicons-exerpt-view',
			'dashicons-hammer',
			'dashicons-art',
			'dashicons-migrate',
			'dashicons-performance',
			'dashicons-universal-access',
			'dashicons-universal-access-alt',
			'dashicons-tickets',
			'dashicons-nametag',
			'dashicons-clipboard',
			'dashicons-heart',
			'dashicons-megaphone',
			'dashicons-schedule',
			'dashicons-wordpress',
			'dashicons-wordpress-alt',
			'dashicons-pressthis',
			'dashicons-update',
			'dashicons-screenoptions',
			'dashicons-info',
			'dashicons-cart',
			'dashicons-feedback',
			'dashicons-cloud',
			'dashicons-translation',
			'dashicons-tag',
			'dashicons-category',
			'dashicons-archive',
			'dashicons-tagcloud',
			'dashicons-text',
			'dashicons-media-archive',
			'dashicons-media-audio',
			'dashicons-media-code',
			'dashicons-media-default',
			'dashicons-media-document',
			'dashicons-media-interactive',
			'dashicons-media-spreadsheet',
			'dashicons-media-text',
			'dashicons-media-video',
			'dashicons-playlist-audio',
			'dashicons-playlist-video',
			'dashicons-yes',
			'dashicons-no',
			'dashicons-no-alt',
			'dashicons-plus',
			'dashicons-plus-alt',
			'dashicons-minus',
			'dashicons-dismiss',
			'dashicons-marker',
			'dashicons-star-filled',
			'dashicons-star-half',
			'dashicons-star-empty',
			'dashicons-flag',
			'dashicons-share',
			'dashicons-share1',
			'dashicons-share-alt',
			'dashicons-share-alt2',
			'dashicons-twitter',
			'dashicons-rss',
			'dashicons-email',
			'dashicons-email-alt',
			'dashicons-facebook',
			'dashicons-facebook-alt',
			'dashicons-networking',
			'dashicons-googleplus',
			'dashicons-location',
			'dashicons-location-alt',
			'dashicons-camera',
			'dashicons-images-alt',
			'dashicons-images-alt2',
			'dashicons-video-alt',
			'dashicons-video-alt2',
			'dashicons-video-alt3',
			'dashicons-vault',
			'dashicons-shield',
			'dashicons-shield-alt',
			'dashicons-sos',
			'dashicons-search',
			'dashicons-slides',
			'dashicons-analytics',
			'dashicons-chart-pie',
			'dashicons-chart-bar',
			'dashicons-chart-line',
			'dashicons-chart-area',
			'dashicons-groups',
			'dashicons-businessman',
			'dashicons-id',
			'dashicons-id-alt',
			'dashicons-products',
			'dashicons-awards',
			'dashicons-forms',
			'dashicons-testimonial',
			'dashicons-portfolio',
			'dashicons-book',
			'dashicons-book-alt',
			'dashicons-download',
			'dashicons-upload',
			'dashicons-backup',
			'dashicons-clock',
			'dashicons-lightbulb',
			'dashicons-microphone',
			'dashicons-desktop',
			'dashicons-tablet',
			'dashicons-smartphone',
			'dashicons-smiley'
		);
	}

	/**
	 * admin_init()
	 * 
	 * Called when the field is initialized. (back-end)
	 * 
	 */
	/*
	function admin_init() {
		// Add another Underscore template
		// $this->add_template( $this->get_type() . '-Description', array( $this, 'template_description' ) );

		parent::admin_init(); // do not delete
	}
	*/

	/**
	 * init()
	 * 
	 * Called when the field is initialized. (back-end, front-end)
	 * Useful for hooking up to front-end hooks. 
	 * 
	 */
	/*
	function init() {
		parent::init(); // do not delete
	}
	*/
}

